import Head from "next/head";
import Image from "next/image";

import { Typography } from "@mui/material";
import { Eth, VerifiedIcon } from "nftCollections/components/Icons";
import { convertToShortForm, formatEtherValue } from "nftCollections/utils";
import styles from "nftCollections/styles/Collection.module.css";

const collection = {
  id: "eth:azuki-test",
  chain: "eth",
  contract: "azuki-test",
  name: "Azuki Test",
  thumbnail:
    "https://i.seadn.io/gae/H8jOCJuQokNqGBpkBN5wk1oZwO7LM8bNnrHCaekV2nKjnCqw6UB5oaH8XyNeBDj6bA_n1mjejzhFQUP3O1NfjFLHr3FOaeHcTOOT?w=500&auto=format",
  coverImage:
    "https://i.seadn.io/gae/O0XkiR_Z2--OPa_RA6FhXrR16yBOgIJqSLdHTGA0-LAhyzjSYcb3WEPaCYZHeh19JIUEAUazofVKXcY2qOylWCdoeBN6IfGZLJ3I4A?w=2400&auto=format",
  brand: { id: 1, name: "Test Labs" },
  mintPrice: "80000000000000000",
  mintedAt: "2022-02-14T14:00:00.000Z",
  creatorsFee: 500,
  verified: true,
  spam: false,
  stats: {
    items: 10000,
    owners: 3456,
    floorPrice: "139000000000000000",
    floorPriceDelta: 0.96,
    volume24h: "-2098800000000000000",
    volume24hDelta: 2.62,
  },
  ts: 1685896317914,
};

export default function Collection() {
  return (
    <>
      <Head>
        <title>Azumi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.container}>
        <div className={styles.root}>
          <img
            src={collection.coverImage}
            className={styles.coverImage}
            alt={collection.name}
          />
          <div className={styles.content}>
            {/* <HandIcon /> */}

            <Typography className={styles.rockingHand}>🤘</Typography>

            <a href="https://uncommon.me/" className={styles.uncommonLink}>
              <Typography variant="h3">uncommon.me</Typography>
            </a>

            <div className={styles.thumbnailWrapper}>
              <Image
                src={collection.thumbnail}
                width={80}
                height={80}
                alt={collection.thumbnail}
                className={styles.thumbnail}
              />
            </div>
            <Typography variant="h3" className={styles.title}>
              {collection.name} <VerifiedIcon className={styles.verifiedIcon} />
            </Typography>

            <div className={styles.dataWrapper}>
              <div className={styles.data}>
                <Typography className={styles.dataText} variant="h5">
                  <strong>Floor price</strong>
                </Typography>
                <Typography className={styles.dataTextValue} variant="h5">
                  {formatEtherValue(collection.stats.floorPrice)}{" "}
                  <Eth className={styles.ethIcon} />
                </Typography>
              </div>
              <div className={styles.data}>
                <Typography className={styles.dataText} variant="h5">
                  <strong>24h vol</strong>
                </Typography>
                <Typography className={styles.dataTextValue} variant="h5">
                  {formatEtherValue(collection.stats.volume24h)}{" "}
                  <Eth className={styles.ethIcon} />
                </Typography>
              </div>
              <div className={styles.data}>
                <Typography className={styles.dataText} variant="h5">
                  <strong>Items</strong>
                </Typography>
                <Typography className={styles.dataTextValue} variant="h5">
                  {convertToShortForm(collection.stats.items)}
                </Typography>
              </div>
              <div className={styles.data}>
                <Typography className={styles.dataText} variant="h5">
                  <strong>Owners</strong>
                </Typography>
                <Typography className={styles.dataTextValue} variant="h5">
                  {convertToShortForm(collection.stats.owners)}
                </Typography>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
